name: Chuck Joke

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Use Node.js ${{ matrix.node-version }}
      - uses: jacckmark/chuck_norris_joke_action@master
          with:
            sendingEmailAddress: ${{secrets.SENDING_MAIL_ADDRESS}}
            sendingEmailPass: ${{secrets.SENDING_MAIL_PASSWORD}}
            receivingEmailAddress: ${{secrets.RECEIVING_MAIL_ADDRESS}}
      - uses: actions/setup-node@v1
          with:
            node-version: "12.X"
      - run: npm install
      - run: npm run build --if-present
        env:
          CI: true
