name: Chuck Joke

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Use Node.js ${{ matrix.node-version }}
      - run: npm install
      - uses: jacckmark/chuck_norris_joke_action@master
        name: use chuck_norris_joke_action
        with:
          github-access-token: ${{secrets.GITHUB_ACCESS_TOKEN}}
          translation-api-token: ${{secrets.TRANSLATION_API_TOKEN}}
      - uses: actions/setup-node@v1
        name: use actions/setup-node
        with:
          node-version: "12.X"
      - run: npm run build --if-present
        env:
          CI: true
